name: Tests

env:
    EXTNAME: cube/matomoanalytics   # Your extension vendor/package name
    SNIFF: 1             # Run code sniffer on your code? 1 or 0
    IMAGE_ICC: 1         # Run icc profile sniffer on your images? 1 or 0
    EPV: 1               # Run EPV (Extension Pre Validator) on your code? 1 or 0
    EXECUTABLE_FILES: 1  # Run check for executable files? 1 or 0
    PHPBB_BRANCH: 3.3.x  # The phpBB branch to run tests on

on:
    push:
        branches:        # Run tests when commits are pushed to these branches in your repo
            - main
            - develop
            - dev/*
    pull_request:        # Run tests when pull requests are made on these branches in your repo
        branches:
            - main
            - develop
            - dev/*

jobs:
    call-tests:
        name: Extension tests
        uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@3.3.x
        with:
            EXTNAME: phpbb/googleanalytics # Your extension vendor/package name
            CODECOV: 1                     # Run code coverage via codecov? 1 or 0
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # Do not change this
